fail_on_violations: true

scss:
  config_file: .scss-lint.yml
  enabled: true
  exclude:
    - "scss/base/_normalize.scss"

javascript:
  enabled: true
  config_file: .jshintrc

jscs:
  enabled: true
  config_file: .jscsrc

ruby:
  enabled: false
