# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://figuration.org
encoding:         UTF-8
exclude:          [assets/scss/]

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  3.0.3
repo:             https://github.com/cast-org/figuration
changelog:        https://github.com/cast-org/figuration/releases/tag/v3.0.3
twitter:          https://twitter.com/figuration_org


# Downloads
download:
  source:         https://github.com/cast-org/figuration/archive/v3.0.3.zip
  dist:           https://github.com/cast-org/figuration/releases/download/v3.0.3/figuration-v3.0.3-dist.zip


# CDN settings
# See https://www.srihash.org for info on how to generate the hashes
cdn:
  css:          https://cdn.jsdelivr.net/npm/figuration@3.0.3/dist/css/figuration.min.css
  css_hash:     "sha384-dd4dRfo/aHHKjwJ6DH0helo0RGm5SfuAewSIojP0I/5TtWBasod6Mlli1hw0QVn5"
  js:           https://cdn.jsdelivr.net/npm/figuration@3.0.3/dist/js/figuration.min.js
  js_hash:      "sha384-uBg0sdYZVuXA40V/ZHGk4ajknDl1bitxn3Y8AG3VFsvTUe3lfK6Dyd93aSgYX4rx"
  css_rtl:      https://cdn.jsdelivr.net/npm/figuration@3.0.3/dist/css/figuration-rtl.min.css
  css_rtl_hash: "sha384-WstelInoyvL4ow6AnmtUS6pFE/1y4klbJhfioS5U2aAhTl5DIsSXl9ub1/5ticjp"
  jquery:       https://code.jquery.com/jquery-3.2.1.min.js
  jquery_hash:  "sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
  fontawe:      https://use.fontawesome.com/releases/v5.0.0/css/all.css
  fontawe_hash: "sha384-uxfBsD39FjU4+TZrrZ9Vt8UE2NF/+WGix2XNBeEcQboNY7uzrGQ32DVVLZX+UfJD"
  mutate:       https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/MutationObserver.min.js
  mutate_hash:  "sha384-8HHYYRe45k4Xq40fi/cZaaby4FJgnOOVmnRzX3OWtwpfiUPfx7tnK2QkDPuIRGm0"
