# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://figuration.org
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  1.3.0
repo:             https://github.com/cast-org/figuration

# Downloads
download:
  source:         https://github.com/cast-org/figuration/archive/v1.3.0.zip
  dist:           https://github.com/cast-org/figuration/releases/download/v1.3.0/figuration-1.3.0-dist.zip


# CDN settings
# See https://www.srihash.org for info on how to generate the hashes
cdn:
  css:          https://cdn.jsdelivr.net/figuration/1.3.0/css/figuration.min.css
  css_hash:     "sha384-QGoOlSi7NTKCPEYxZxZ/cBTKgaA1sgj2MKSsTd7i6IQLk1LL9dDmTcQPAap7TG3C"
  js:           https://cdn.jsdelivr.net/figuration/1.3.0/js/figuration.min.js
  js_hash:      "sha384-dhf4AQwEoYTs4kTw6+HaeZ5Dqgcc8Y3IUq3FNLKLvrUT9YdUQoncLlw/3g/Axvs7"
  jquery:       https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js
  jquery_hash:  "sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
  fontawe:      https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css
  fontawe_hash: "sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1"
