# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://figuration.org
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  1.3.1
repo:             https://github.com/cast-org/figuration

# Downloads
download:
  source:         https://github.com/cast-org/figuration/archive/v1.3.1.zip
  dist:           https://github.com/cast-org/figuration/releases/download/v1.3.1/figuration-1.3.1-dist.zip


# CDN settings
# See https://www.srihash.org for info on how to generate the hashes
cdn:
  css:          https://cdn.jsdelivr.net/figuration/1.3.1/css/figuration.min.css
  css_hash:     "sha384-jGVJM2f0Zq8UhosAIjZaco0wpYiPPPZ7FcUXmZUjhTLxlLtKS9BvPaGh+LFnpr2z"
  js:           https://cdn.jsdelivr.net/figuration/1.3.1/js/figuration.min.js
  js_hash:      "sha384-rZeLN+g9btcV0KAPEvhS0f2ltBtQ81IuEUrc7yA6kQYQK6Kx1n478ycS3qoDbOOG"
  jquery:       https://code.jquery.com/jquery-3.1.1.min.js
  jquery_hash:  "sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
  fontawe:      https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  fontawe_hash: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
