# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://figuration.org
encoding:         UTF-8
exclude:          [assets/scss/]

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  3.0.2
repo:             https://github.com/cast-org/figuration
changelog:        https://github.com/cast-org/figuration/releases/tag/v3.0.2
twitter:          https://twitter.com/figuration_org


# Downloads
download:
  source:         https://github.com/cast-org/figuration/archive/v3.0.2.zip
  dist:           https://github.com/cast-org/figuration/releases/download/v3.0.2/figuration-v3.0.2-dist.zip


# CDN settings
# See https://www.srihash.org for info on how to generate the hashes
cdn:
  css:          https://cdn.jsdelivr.net/npm/figuration@3.0.2/dist/css/figuration.min.css
  css_hash:     "sha384-uuz8/5oOqrlEslRgVhwq0n/C0eFjPssUek6y3bcU5D1thC0DPwIEx5Lr1tPUCnfn"
  js:           https://cdn.jsdelivr.net/npm/figuration@3.0.2/dist/js/figuration.min.js
  js_hash:      "sha384-bXQJnSrAuWmG6USyJHAtIjI4no8Ff5bUIpOR6R/SvrNGukxG+SKLmeSU5FZxXXbu"
  css_rtl:      https://cdn.jsdelivr.net/npm/figuration@3.0.2/dist/css/figuration-rtl.min.css
  css_rtl_hash: "sha384-rlKsiFOwLSTHA/2H8/QNqZuKjLGwbveksYztn5+fXjZitTdzHbhPofqt2vgHkk7G"
  jquery:       https://code.jquery.com/jquery-3.2.1.min.js
  jquery_hash:  "sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
  fontawe:      https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
  fontawe_hash: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
  mutate:       https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/MutationObserver.min.js
  mutate_hash:  "sha384-8HHYYRe45k4Xq40fi/cZaaby4FJgnOOVmnRzX3OWtwpfiUPfx7tnK2QkDPuIRGm0"
