# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://figuration.org
encoding:         UTF-8
exclude:          [assets/scss/]

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
current_version:  4.0.0-alpha.1
repo:             https://github.com/cast-org/figuration/tree/v4-dev
changelog:        https://github.com/cast-org/figuration/releases/tag/v4.0.0-alpha.1
twitter:          https://twitter.com/figuration_org


# Downloads
download:
  source:         https://github.com/cast-org/figuration/archive/v4.0.0-alpha.1.zip
  dist:           https://github.com/cast-org/figuration/releases/download/v4.0.0-alpha.1/figuration-4.0.0-alpha.1-dist.zip


# CDN settings
# See https://www.srihash.org for info on how to generate the hashes
cdn:
  css:          https://cdn.jsdelivr.net/npm/figuration@4.0.0-alpha.1/dist/css/figuration.min.css
  css_hash:     "sha384-qC3Vd8Ump89qtZ5Ll6PSveWCBLJIedyOHcy3hgoMiCT22250U1rT7UPIvdTLVRjL"
  js:           https://cdn.jsdelivr.net/npm/figuration@4.0.0-alpha.1/dist/js/figuration.min.js
  js_hash:      "sha384-4YJ+nmEMuJ6m2VHwZA/FFcSvSMSRO9zhuH2oDi3eo926fVlZo6zNJ24id9nCpaJ7"
  css_rtl:      https://cdn.jsdelivr.net/npm/figuration@4.0.0-alpha.1/dist/css/figuration-rtl.min.css
  css_rtl_hash: "sha384-lLbRsyEEBLI+RvcBAQMGTEiMZIqryEbZdZN0Nk3bYLNckaYjDdXBLbmAAepljYjX"
  jquery:       https://code.jquery.com/jquery-3.3.1.slim.min.js
  jquery_hash:  "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  fontawe:      https://use.fontawesome.com/releases/v5.0.1/css/all.css
  fontawe_hash: "sha384-VVoO3UHXsmXwXvf1kJx2jV3b1LbOfTqKL46DdeLG8z4pImkQ4GAP9GMy+MxHMDYG"
  mutate:       https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/MutationObserver.min.js
  mutate_hash:  "sha384-8HHYYRe45k4Xq40fi/cZaaby4FJgnOOVmnRzX3OWtwpfiUPfx7tnK2QkDPuIRGm0"
